meta_product_name: "Chip In"
meta_title: "Chip In - Find volunteering experiences near you"
meta_description: "Chip in makes it easy to find volunteering opportunities near you. Whether at home or on the go, you contact charities directly. You will meet like-minded individuals and have experiences that you won't forget."
meta_image: "community.jpg" # should exist in `app/assets/images/`
